# Generated by Django 4.1.5 on 2023-02-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_clientes', models.CharField(max_length=40, verbose_name='codigo_clientes')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=40, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=60, verbose_name='Direccion')),
                ('plataforma', models.CharField(max_length=60, verbose_name='Plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(max_length=40, verbose_name='codigo_referencia')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombres')),
                ('modelo', models.CharField(max_length=40, verbose_name='Modelo')),
                ('unidades', models.CharField(max_length=60, verbose_name='unidades')),
                ('preciounidad', models.FloatField(verbose_name='Precio_Unidad')),
                ('precioventa', models.FloatField(verbose_name='Precio_Venta')),
                ('envio', models.FloatField(verbose_name='Envio')),
                ('etsy', models.FloatField(null=True, verbose_name='Etsy')),
                ('wallapop', models.FloatField(null=True, verbose_name='Wallapop')),
                ('ebay', models.FloatField(null=True, verbose_name='Ebay')),
                ('joom', models.FloatField(null=True, verbose_name='Joom')),
                ('amazon', models.FloatField(null=True, verbose_name='Amazon')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(max_length=40, verbose_name='codigo_referencia')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombres')),
                ('modelo', models.CharField(max_length=40, verbose_name='Modelo')),
                ('numserie', models.CharField(max_length=60, verbose_name='numserie')),
                ('precioventa', models.FloatField(verbose_name='precioventa')),
                ('envio', models.FloatField(verbose_name='envio')),
                ('cliente', models.CharField(max_length=60, verbose_name='cliente')),
            ],
        ),
    ]
